zlz:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: renmen321.cn
    port: 3306
    database: pig_counter
    username: root
    password: Aa13873670217
  image:
    save-path: ${working.dir}
  password:
    salt: PigCounter
  redis:
    host: pig-redis
    port: 6379
    password: 123456
    database: 0
    ttlMin: 30
  jwt:
    admin-secret-key: PigCounteraaaaaaaaaaaaaaaaaaaaaaa
    admin-token-name: Authorization
    #过期时间
    admin-ttl: 86400000
  AI: http://fastapi-app:8000