zlz:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: pig_counter
    username: root
    password: 123456
  image:
    save-path: ${working.dir}/images
  password:
    salt: PigCounter
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0