server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB
  ssl:
    enabled: true
    key-store: classpath:ssl/renmen321.cn.jks
    key-store-password: 8f8yrvoo
    key-store-type: JKS
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${zlz.datasource.driver-class-name}
      url: jdbc:mysql://${zlz.datasource.host}:${zlz.datasource.port}/${zlz.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${zlz.datasource.username}
      password: ${zlz.datasource.password}
  data:
    redis:
      port: ${zlz.redis.port}
      host: ${zlz.redis.host}
      database: ${zlz.redis.database}
      password: ${zlz.redis.password}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zlz.entity
  configuration:
    map-underscore-to-camel-case: true
jwt:
  admin-secret-key: ${zlz.jwt.admin-secret-key}
  admin-token-name: ${zlz.jwt.admin-token-name}
    #过期时间
  admin-ttl: ${zlz.jwt.admin-ttl}
#logging:
#  level:
#    com.zlz.pigcounter.mapper: debug